from django.urls import path
from . import views


app_name = 'admin_panel'
urlpatterns = [
    path('' , views.index, name='index'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/create/', views.course_create, name='course_create'),
    path('courses/<int:pk>/update/', views.course_update, name='course_update'),
    path('courses/<int:pk>/delete/', views.course_delete, name='course_delete'),
    path('teachers/', views.teacher_list, name='teacher_list'),
    path('teachers/create/', views.teacher_create, name='teacher_create'),
    path('teachers/<int:pk>/update/', views.teacher_update, name='teacher_update'),
    path('teachers/<int:pk>/delete/', views.teacher_delete, name='teacher_delete'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/create/', views.category_create, name='category_create'),
    path('categories/<int:pk>/update/', views.category_update, name='category_update'),
    path('categories/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('articles/', views.article_list, name='article_list'),
    path('articles/create/', views.article_create, name='article_create'),
    path('articles/<int:pk>/update/', views.article_update, name='article_update'),
    path('articles/<int:pk>/delete/', views.article_delete, name='article_delete'),
    path('authors/', views.author_list, name='author_list'),
    path('authors/create/', views.author_create, name='author_create'),
    path('authors/<int:pk>/update/', views.author_update, name='author_update'),
    path('authors/<int:pk>/delete/', views.author_delete, name='author_delete'),
    path('contacts/', views.contact_list, name='contact_list'),
    path('contacts/<int:pk>/', views.contact_detail, name='contact_detail'),
    path('tickets/', views.ticket_list, name='ticket_list'),
    path('tickets/<int:pk>/', views.ticket_detail, name='ticket_detail'),
    path('site-settings/', views.site_setting_list, name='site_setting_list'),
    path('site-settings/update/<int:pk>/', views.site_setting_update, name='site_setting_update'),
    path('footer-boxes/', views.footer_box_list, name='footer_box_list'),
    path('footer-boxes/create/', views.footer_box_create, name='footer_box_create'),
    path('footer-boxes/update/<int:pk>/', views.footer_box_update, name='footer_box_update'),
    path('footer-boxes/delete/<int:pk>/', views.footer_box_delete, name='footer_box_delete'),
    path('footer-links/', views.footer_link_list, name='footer_link_list'),
    path('footer-links/create/', views.footer_link_create, name='footer_link_create'),
    path('footer-links/update/<int:pk>/', views.footer_link_update, name='footer_link_update'),
    path('footer-links/delete/<int:pk>/', views.footer_link_delete, name='footer_link_delete'),
    path('banners/', views.banner_list, name='banner_list'),
    path('banners/create/', views.banner_create, name='banner_create'),
    path('banners/update/<int:pk>/', views.banner_update, name='banner_update'),
    path('banners/delete/<int:pk>/', views.banner_delete, name='banner_delete'),
    path('discount/', views.discount_list, name='discount_list'),
    path('discount/add/', views.discount_create, name='discount_create'),
    path('discount/<int:pk>/edit/', views.discount_update, name='discount_update'),
    path('discount/<int:pk>/delete/', views.discount_delete, name='discount_delete'),
    path('orders/', views.order_list, name='order_list'),
    path('orders/<int:pk>/', views.order_detail, name='order_detail'),
]