# Generated by Django 5.2 on 2025-09-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='is_internal',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='به روزرسانی شده در'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='به روزرسانی شده در'),
        ),
    ]
