# Generated by Django 5.2 on 2025-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/profile/Profile.png', null=True, upload_to='images/profile', verbose_name='تصویر پروفایل'),
        ),
    ]
